-- テーブルの削除
DROP TABLE MESSAGES;
DROP TABLE USERS;
DROP TABLE CHAT_ROOMS;

-- テーブルの作成
CREATE TABLE USERS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE CHAT_ROOMS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE MESSAGES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    ROOM_ID BIGINT NOT NULL,
    CONTENT TEXT NOT NULL,
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (ROOM_ID) REFERENCES CHAT_ROOMS(ID)
);

